
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class lotto extends javax.swing.JFrame {

    public lotto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lottó");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(476, 52, 46, 43);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(540, 52, 46, 43);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(604, 52, 46, 43);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(668, 52, 46, 43);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(420, 52, 46, 43);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 180, 890, 357);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Írd be a számaidat!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 0, 380, 40);

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("MEHET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(445, 106, 232, 48);

        jButton2.setText("ÚJRA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(966, 65, 93, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\lotto\\hatterkep.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1230, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int db1 = 0;
            int db2 = 0;
            int db3 = 0;
            int db4 = 0;
            int db5 = 0;

            //input nyerőszámok beolvasása
            String a = jTextField5.getText();
            String b = jTextField1.getText();
            String c = jTextField2.getText();
            String d = jTextField3.getText();
            String f = jTextField4.getText();

            //hibakezelés
            //csak akkor fusson le a program ha minden mező ki van töltve:
            if (!(a.isEmpty() || b.isEmpty() || c.isEmpty() || d.isEmpty() || f.isEmpty())) {
                //ha nem számot adott meg (try-catchel)

                int tempa = Integer.parseInt(a);
                int tempb = Integer.parseInt(b);
                int tempc = Integer.parseInt(c);
                int tempd = Integer.parseInt(d);
                int tempf = Integer.parseInt(f);

                //csak 1-99 közötti számokkal működjön
                if ((Integer.parseInt(a) > 0 && Integer.parseInt(a) < 91) && (Integer.parseInt(b) > 0 && Integer.parseInt(b) < 91) && (Integer.parseInt(c) > 0 && Integer.parseInt(c) < 91)
                        && (Integer.parseInt(f) > 0 && Integer.parseInt(d) < 91) && (Integer.parseInt(f) > 0 && Integer.parseInt(f) < 91)) {
                    //ne legyen két egyforma szám benne     
                    if (!a.equals(b) && !a.equals(c) && !a.equals(d) && !a.equals(f)
                            && !b.equals(c) && !b.equals(d) && !b.equals(f)
                            && !c.equals(d) && !c.equals(f)
                            && !d.equals(f)) {

                        int vegdb = 0;
                        for (int i = 0; i < lista.size(); i++) {

                            if (lista.get(i).nyeroszamok.contains(" " + a + " ")) {
                                db1 = 1;
                            } else {

                            }
                            if (lista.get(i).nyeroszamok.contains(" " + b + " ")) {
                                db2 = 1;

                            } else {

                            }
                            if (lista.get(i).nyeroszamok.contains(" " + c + " ")) {
                                db3 = 1;

                            } else {

                            }
                            if (lista.get(i).nyeroszamok.contains(" " + d + " ")) {
                                db4 = 1;

                            } else {

                            }
                            if (lista.get(i).nyeroszamok.contains(" " + f + " ")) {
                                db5 = 1;

                            } else {

                            }
                            vegdb = db1 + db2 + db3 + db4 + db5;
                            db1 = 0;
                            db2 = 0;
                            db3 = 0;
                            db4 = 0;
                            db5 = 0;

                            if (vegdb < 2) {
                            } else if (vegdb == 2 && lista.get(i).kettonyeremeny != 0) {
                                jTextArea1.append("TALÁLAT:  2       ÉV: " + lista.get(i).ev + "            HÉT: " + lista.get(i).het + "             DÁTUM:  " + lista.get(i).huzasdatum + "            NYEREMÉNY: " + lista.get(i).kettonyeremeny + " Ft" + "           NYERŐSZÁMOK:   " + lista.get(i).nyeroszamok.replace("#", ",") + "        " + "\n");
                            } else if (vegdb == 3 && lista.get(i).haromnyeremeny != 0) {
                                jTextArea1.append("TALÁLAT:  3       ÉV: " + lista.get(i).ev + "            HÉT: " + lista.get(i).het + "             DÁTUM:  " + lista.get(i).huzasdatum + "            NYEREMÉNY: " + lista.get(i).haromnyeremeny + " Ft" + "           NYERŐSZÁMOK:   " + lista.get(i).nyeroszamok.replace("#", ",") + "        " + "\n");
                            } else if (vegdb == 4 && lista.get(i).negynyeremeny != 0) {
                                jTextArea1.append("TALÁLAT:  4       ÉV: " + lista.get(i).ev + "            HÉT: " + lista.get(i).het + "             DÁTUM:  " + lista.get(i).huzasdatum + "            NYEREMÉNY: " + lista.get(i).negynyeremeny + " Ft" + "            NYERŐSZÁMOK:   " + lista.get(i).nyeroszamok.replace("#", ",") + "        " + "\n");
                            } else if (vegdb == 5 && lista.get(i).otnyeremeny != 0) {
                                jTextArea1.append("TALÁLAT:  5       ÉV: " + lista.get(i).ev + "            HÉT: " + lista.get(i).het + "             DÁTUM:  " + lista.get(i).huzasdatum + "            NYEREMÉNY: " + lista.get(i).otnyeremeny + " Ft" + "              NYERŐSZÁMOK:   " + lista.get(i).nyeroszamok.replace("#", ",") + "        " + "\n");
                            }
                        }

                        //hibaüzenetek
                    } else {
                        JOptionPane.showMessageDialog(jLabel1, "Ne adj meg több azonos számot!", "HIBA!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(jLabel1, "Nem helyes adatokat adtál meg!", "HIBA!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(jLabel1, "Nem adtad meg az összes számot!", "HIBA!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jLabel1, "Csak számot adj meg, más karaktereket ne!", "HIBA!", JOptionPane.ERROR_MESSAGE);
            //System.out.println(ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.selectAll();
        jTextField1.selectAll();
        jTextField2.selectAll();
        jTextField3.selectAll();
        jTextField4.selectAll();
        jTextField5.selectAll();

        jTextArea1.replaceSelection("");
        jTextField1.replaceSelection("");
        jTextField2.replaceSelection("");
        jTextField3.replaceSelection("");
        jTextField4.replaceSelection("");
        jTextField5.replaceSelection("");

    }//GEN-LAST:event_jButton2ActionPerformed

    public ArrayList<Integer> inputlista = new ArrayList<>();

    public static class adatok {

        int ev;
        int het;
        String huzasdatum;
        Long otnyeremeny;
        Long negynyeremeny;
        int haromnyeremeny;
        int kettonyeremeny;
        String nyeroszamok;

        public adatok(int ev, int het, String huzasdatum, Long otnyeremeny, Long negynyeremeny, int haromnyeremeny, int kettonyeremeny, String nyeroszamok) {
            this.ev = ev;
            this.het = het;
            this.huzasdatum = huzasdatum;
            this.otnyeremeny = otnyeremeny;
            this.negynyeremeny = negynyeremeny;
            this.haromnyeremeny = haromnyeremeny;
            this.kettonyeremeny = kettonyeremeny;
            this.nyeroszamok = nyeroszamok;
        }

    }
    public static ArrayList<adatok> lista = new ArrayList<>();

    public static void beolvas(ArrayList<adatok> lista) throws FileNotFoundException {
        Scanner fileinput = new Scanner(new File("lotto.csv"));
        String elsosor = fileinput.nextLine();
        while (fileinput.hasNextLine()) {
            String data = fileinput.nextLine();
            String tomb[] = data.split(";");
            String nyerosamok = " " + tomb[7] + " # " + tomb[8] + " # " + tomb[9] + " # " + tomb[10] + " # " + tomb[11] + " ";
            lista.add(new adatok(Integer.parseInt(tomb[0]), Integer.parseInt(tomb[1]), tomb[2],
                    Long.parseLong(tomb[3]), Long.parseLong(tomb[4]), Integer.parseInt(tomb[5]), Integer.parseInt(tomb[6]),
                    nyerosamok
            ));

        }
        fileinput.close();

    }

    public static void main(String args[]) throws FileNotFoundException {
        beolvas(lista);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lotto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lotto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
